name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Node.js dependencies
        run: npm ci
      - name: Compile TypeScript files
        run: npm run build
      - name: Run tests
        run: npm test
